version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mobility
    ports:
      - "5432:5432"
    networks:
      - app-network

  api-mobility:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    container_name: api-mobility
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
    extra_hosts:
      - "localhost:host-gateway"
    command: npm run dev

networks:
  app-network:
    driver: bridge
